app_home:
    path: /
    controller: App\Controller\HomeController::index

app_register:
    path: /registration
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_forgot_password_request:
    path: /forgot-password
    controller: App\Controller\ResetPasswordController::request

app_check_email:
    path: /forgot-password/verify/email
    controller: App\Controller\ResetPasswordController::checkEmail

app_reset_password:
    path: /forgot-password/reset-password/{token}
    controller: App\Controller\ResetPasswordController::reset

app_trick_index:
    path: /tricks
    controller: App\Controller\TrickController::index

app_trick_new:
    path: /tricks/new
    controller: App\Controller\TrickController::new

#app_account:
#    path: /mon-compte
#    controller: App\Controller\AccountController::index
#
#app_account_edit:
#    path: /mon-compte/modifier
#    controller: App\Controller\AccountController::edit
#
#app_account_password:
#    path: /mon-compte/modifier-mot-de-passe
#    controller: App\Controller\AccountController::editPassword
#
#app_account_delete:
#    path: /mon-compte/supprimer
#    controller: App\Controller\AccountController::delete