app_home:
    path: /
    controller: App\Controller\HomeController::index

app_register:
    path: /registration
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_forgot_password_request:
    path: /forgot-password
    controller: App\Controller\ResetPasswordController::request

app_check_email:
    path: /forgot-password/verify/email
    controller: App\Controller\ResetPasswordController::checkEmail

app_reset_password:
    path: /forgot-password/reset-password/{token}
    controller: App\Controller\ResetPasswordController::reset

app_trick_index:
    path: /tricks
    controller: App\Controller\TrickController::index

app_trick_new:
    path: /tricks/new
    controller: App\Controller\TrickController::new

app_trick_show:
    path: /tricks/{slug}
    controller: App\Controller\TrickController::show

app_trick_edit:
    path: /tricks/{slug}/edit
    controller: App\Controller\TrickController::edit

app_trick_delete:
    path: /tricks/{slug}/delete
    controller: App\Controller\TrickController::delete

app_profile_edit:
    path: /profile/edit
    controller: App\Controller\ProfileController::edit

app_media_delete:
    path: /media/{id}/delete
    controller: App\Controller\MediaController::delete

app_comment_delete:
    path: /comment/{id}/delete
    controller: App\Controller\CommentController::delete
