app_home:
    path: /
    controller: App\Controller\HomeController::index

register:
    path: /inscription
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_login:
    path: /connexion
    controller: App\Controller\SecurityController::login

app_logout:
    path: /deconnexion
    controller: App\Controller\SecurityController::logout